// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kiyumuplwhmsghlaundb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpeXVtdXBsd2htc2dobGF1bmRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzA3NDEsImV4cCI6MjA3MDE0Njc0MX0.JQHZjhiRdLrePegQQj6vsaCZ_ZJebbg0ZLzSMqWULuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});